### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by adam-drewery** [dejandjenic/BlazorPlaygroundElectron#1]
Hi :) Thanks for this, its exactly the kind of thing I was looking for. How do I run it though? When I do `npm start` in the `electron-app` directory, it fails to find `index.html`:

```
(node:12192) electron: Failed to load URL: file:///C:/Users/adre/Downloads/BlazorPlaygroundElectron-main/BlazorPlaygroundElectron-main/electron-app/index.html with error: ERR_FILE_NOT_FOUND
```

**Comment by dejandjenic** [comment]
you run blazor application in development mode as usual, when your development is finished , usually as part of the dpeloyment process you publish blazor application to static files and then connection to electron kicks in.
you can take a look at deployment stepp in this repo https://github.com/dejandjenic/BlazorPlaygroundElectron/blob/main/.github/workflows/blazor-electron-action.yml

**Comment by dejandjenic** [comment]
please check this article https://www.dejandjenic.com/blogs/publishing-blazor-wasm-with-electron-js.html

**Comment by adam-drewery** [comment]
Thanks Dejan! This makes a lot of sense- I was trying to debug the electron app as a whole but it seems reasonable to just run it as a regular Blazor app when debugging locally. I'll close the issue. Have a nice weekend. :)
